apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: marketresearch
  namespace: gproject
  labels:
    name: marketresearch
spec:
  replicas: 1
  selector:
    matchLabels:
      name: marketresearch
  template:
    metadata:
      labels:
        name: marketresearch
    spec:
      restartPolicy: Always
      containers:
      - image: giovanejr/gproject-public
        name: marketresearch
        imagePullPolicy: Always
        ports:
        - name: marketresearch
          containerPort: 8080
          protocol: TCP
        env:
        - name: ENV
          value: production
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 80m
            memory: 64Mi
        securityContext:
          privileged: true
        lifecycle:
          postStart:
            exec:
              command: ["gcsfuse", "-o", "nonempty,allow_other", "--uid=33", "--gid=33", "--dir-mode", "750", "--file-mode", "640", "fs_market_research", "/var/www/html/files"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/var/www/html/files"]

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: marketresearch
  name: marketresearch
  namespace: gproject
spec:
  ports:
  - name: marketresearch
    port: 8080
    protocol: TCP
  selector:
    name: marketresearch
  sessionAffinity: None
  type: ClusterIP
