apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: public
  namespace: gproject
  labels:
    name: public
spec:
  replicas: 1
  selector:
    matchLabels:
      name: public
  template:
    metadata:
      labels:
        name: public
    spec:
      restartPolicy: Always
      containers:
      - image: giovanejr/gproject-public:18
        name: public
        imagePullPolicy: Always
        ports:
        - name: public
          containerPort: 8080
          protocol: TCP
        env:
        - name: ENV
          value: production
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          privileged: true
        lifecycle:
#          preStart:
#            exec:
#              command: ["sed", "-i", "s:fserver:public:g", "/etc/apache2/apache2.conf"]
          postStart:
            exec:
              command: ["gcsfuse", "-o", "nonempty,allow_other", "--uid=33", "--gid=33", "--dir-mode", "750", "--file-mode", "640", "fs_public", "/var/www/html/files"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/var/www/html/files"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: public
  name: public
  namespace: gproject
spec:
  ports:
  - name: public
    port: 8080
    protocol: TCP
  selector:
    name: public
  sessionAffinity: None
  type: ClusterIP
